#!/bin/bash
# This script attempts to work around broken "start minimised" Discord functionality.
# Since the option within the program itself does not work (at least for me), this little
# script starts alongside Dicsord and minimises its window if it appears within a minute.

for i in {1..60}; do
	for WINDOW_ID in $(xdotool search --onlyvisible --class "discord"); do
		if (xprop -id $WINDOW_ID | grep -Eq 'WM_WINDOW_ROLE.+browser-window'); then
			xdotool windowunmap $WINDOW_ID
			break 2
		fi
		sleep 1
	done
done
